// Format: "English|Translation 1|Translation 2|Translation 3"
const RAW = [
"Advertisement|Anuncio|Publicidad|Aviso",
"Air|Aire|Aire atmosférico|Viento",
"Airplane|Avión|Aeroplano|Aeronave",
"Album|Álbum|Colección|Libro de fotos",
"Alien|Extraterrestre|Alienígena|Ser de otro planeta",
"Alley|Callejón|Pasadizo|Callejuela",
"America|América|Estados Unidos|Continente americano",
"Ants|Hormigas|Hormigas pequeñas|Colonia de hormigas",
"Aquarium|Acuario|Pecera|Tanque de peces",
"Art|Arte|Obra artística|Expresión artística",
"Artificial Flavoring|Saborizante artificial|Aromatizante artificial|Esencia artificial",
"Asia|Asia|Continente asiático|Región asiática",
"Atlas|Atlas|Libro de mapas|Colección de mapas",
"Atom|Átomo|Partícula|Partícula atómica",
"Attic|Ático|Buhardilla|Desván",
"Baby|Bebé|Bebito|Infante",
"Bacteria|Bacteria|Organismo Unicelular|Organismo Procariota",
"Balloon|Globo|Globo de aire|Globo de fiesta",
"Bar|Bar|Barra|Cantina",
"Barn|Granero|Establo|Cobertizo",
"Bathroom|Baño|Cuarto de baño|Sanitario",
"Bathtub|Bañera|Tina|Tina de baño",
"Bed|Cama|Lecho|Camastro",
"Bedroom|Dormitorio|Habitación|Recámara",
"Bee|Abeja|Insecto|Abejita",
"Belly Button|Ombligo|Ombligo del vientre|Botón del vientre",
"Black Hole|Agujero negro|Pozo negro|Hoyo negro",
"Blimp|Dirigible|Aerostato|Zeppelin",
"Bone|Hueso|Osamenta|Huesito",
"Book|Libro|Texto|Obra",
"Bottle|Botella|Frasco|Envase",
"Box|Caja|Cajón|Recipiente",
"Boy|Niño|Muchacho|Chico",
"Brain|Cerebro|Encéfalo|Mente",
"Bucket|Cubeta|Balde|Cubo",
"Cage|Jaula|Reja|Enrejado",
"Canyon|Cañón|Barranco|Desfiladero",
"Castle|Castillo|Fortaleza|Palacio fortificado",
"Cat|Gato|Felino|Minino",
"Cavity|Caries|Cavidad|Agujero dental",
"Cell|Célula|Celda|Compartimento",
"Cement|Cemento|Mortero|Material cementicio",
"Cemetery|Cementerio|Camposanto|Panteón",
"Change|Cambio|Transformación|Vuelto",
"Cheeseburger|Hamburguesa con queso|Hamburguesa de queso|Hamburguesa con cheddar",
"Chicken|Pollo|Gallina|Ave",
"China|China|República Popular China|País asiático",
"Chocolate|Chocolate|Cacao|Dulce de chocolate",
"Circle|Círculo|Circunferencia|Redondel",
"Closet|Armario|Clóset|Ropero",
"Club|Club|Asociación|Grupo",
"Coffee|Café|Bebida de café|Taza de café",
"Coffin|Ataúd|Féretro|Sarcófago",
"Color|Color|Tono|Matiz",
"Corner|Esquina|Rincón|Ángulo",
"Danger|Peligro|Riesgo|Amenaza",
"Desk|Escritorio|Mesa de trabajo|Pupitre",
"Diamond|Diamante|Piedra preciosa|Gema",
"Diaper|Pañal|Pañalito|Pañal infantil",
"Dictionary|Diccionario|Léxico|Libro de definiciones",
"DNA|ADN|Ácido desoxirribonucleico|Material genético",
"Dog House|Caseta para perro|Casa de perro|Perrera",
"Drawer|Cajón|Gaveta|Compartimento",
"Dream|Sueño|Ensueño|Ilusión",
"Dryer|Secadora|Secador|Máquina secadora",
"Dumpster|Contenedor de basura|Basurero|Contenedor de desperdicios",
"Dungeon|Mazmorra|Calabozo|Sótano-prisión",
"Dust|Polvo|Polvillo|Suciedad",
"Ear|Oreja|Oído|Pabellón auditivo",
"Earthquake|Terremoto|Sismo|Temblor",
"Egg|Huevo|Huevito|Óvulo",
"Elephant|Elefante|Paquidermo|Elefante grande",
"Email|Correo electrónico|Email|Mensaje electrónico",
"Envelope|Sobre|Envoltorio|Cubierta",
"Eye|Ojo|Mirada|Órgano de la vista",
"Face|Cara|Rostro|Faz",
"Family|Familia|Parientes|Familiares",
"Fear|Miedo|Temor|Pavor",
"Fire|Fuego|Llama|Incendio",
"Fireplace|Chimenea|Hogar|Hogar de fuego",
"Flood|Inundación|Riada|Desbordamiento",
"Fly|Mosca|Insecto volador|Mosquita",
"Fog|Niebla|Neblina|Bruma",
"Foot|Pie|Pata|Extremidad",
"Forest|Bosque|Selva|Arboleda",
"Frame|Marco|Armazón|Estructura",
"France|Francia|República Francesa|País europeo",
"Frog|Rana|Sapo|Anfibio",
"Frying Pan|Sartén|Cacerola|Freidera",
"Galaxy|Galaxia|Sistema galáctico|Conjunto de estrellas",
"Garage|Garaje|Cochera|Aparcamiento",
"Garbage|Basura|Desperdicios|Desechos",
"Garden|Jardín|Huerto|Jardín de plantas",
"Gas|Gas|Combustible|Gasolina",
"Giraffe|Jirafa|Animal de cuello largo|Jirafa africana",
"Girl|Niña|Muchacha|Chica",
"Gold|Oro|Metal precioso|Dorado",
"Golf Ball|Pelota de golf|Bola de golf|Balón de golf",
"Grand Piano|Piano de cola|Piano de concierto|Gran piano",
"Grass|Césped|Hierba|Pasto",
"Gutter|Canaleta|Cuneta|Canal de desagüe",
"Haystack|Pajar|Montón de heno|Pila de heno",
"Head|Cabeza|Testa|Cabeza humana",
"Heart|Corazón|Órgano cardíaco|Corazón humano",
"Hole|Agujero|Hoyo|Orificio",
"Hollywood|Hollywood|La meca del cine|Industria cinematográfica",
"Hope|Esperanza|Ilusión|Esperanza futura",
"Hot Dog|Perro caliente|Hot dog|Salchicha con pan",
"House|Casa|Hogar|Vivienda",
"Ice|Hielo|Escarcha|Agua congelada",
"Jacket|Chaqueta|Chamarra|Abrigo",
"Jam|Mermelada|Confitura|Dulce de fruta",
"Juice|Jugo|Zumo|Néctar",
"Jungle|Selva|Jungla|Bosque tropical",
"Kangaroo|Canguro|Marsupial|Canguro australiano",
"Key|Llave|Clave|Tecla",
"Kitchen|Cocina|Cocina doméstica|Cuarto de cocina",
"Laughter|Risa|Carcajada|Risa sonora",
"Lawyer|Abogado|Licenciado|Jurista",
"Leftovers|Sobras|Restos de comida|Comida sobrante",
"Letter|Carta|Letra|Misiva",
"Library|Biblioteca|Librería|Colección de libros",
"Life|Vida|Existencia|Vitalidad",
"Lightbulb|Bombilla|Foco|Bombillo",
"Limousine|Limusina|Auto de lujo|Coche con chofer",
"Line|Línea|Fila|Renglón",
"Lint|Pelusa|Borra|Fibras de tela",
"Love|Amor|Cariño|Afecto",
"Lunch|Almuerzo|Comida|Comida del mediodía",
"Magazine|Revista|Publicación|Revista periódica",
"Mail|Correo|Correspondencia|Mensajería",
"Mansion|Mansión|Casa señorial|Residencia",
"Memory|Memoria|Recuerdo|Recapitulación",
"Microwave|Microondas|Horno microondas|Horno de microondas",
"Mirror|Espejo|Cristal reflectante|Espejo de pared",
"Money|Dinero|Plata|Efectivo",
"Monkey|Mono|Simio|Monito",
"Moose|Alce|Alce americano|Ciervo gigante",
"Mouth|Boca|Cavidad bucal|Hocico",
"Movie Star|Estrella de cine|Actor famoso|Actriz famosa",
"Mud|Lodo|Barro|Fango",
"Museum|Museo|Galería|Centro museístico",
"Mystery|Misterio|Enigma|Incógnita",
"Neck|Cuello|Nuca|Cerviz",
"Needle|Aguja|Aguja de coser|Alfiler",
"Nest|Nido|Madriguera|Refugio",
"Newspaper|Periódico|Diario|Prensa",
"New York|Nueva York|Ciudad de Nueva York|Nueva York, EE. UU.",
"Nose|Nariz|Olfato|Narizota",
"Nothing|Nada|Ninguna cosa|Cero",
"Nun|Monja|Religiosa|Hermana",
"Ocean|Océano|Mar|Alta mar",
"Oven|Horno|Horno de cocina|Horno para hornear",
"Parade|Desfile|Parada|Procesión",
"Paradise|Paraíso|Edén|Lugar paradisíaco",
"Paris|París|Ciudad de París|Capital francesa",
"Parking Lot|Estacionamiento|Aparcamiento|Parqueo",
"Partridge|Perdiz|Ave de caza|Perdiz común",
"Pear Tree|Peral|Árbol de pera|Árbol de peras",
"Pickle|Pepinillo|Encurtido|Pepino encurtido",
"Picture|Imagen|Fotografía|Cuadro",
"Pill|Pastilla|Píldora|Tableta",
"Piñata|Piñata|Olla de barro decorada|Figura para romper",
"Pocket|Bolsillo|Bolsillo de ropa|Compartimento",
"Poison|Veneno|Tóxico|Sustancia venenosa",
"Poodle|Caniche|Poodle|Perro caniche",
"Pool|Piscina|Alberca|Pileta",
"Pot|Olla|Maceta|Recipiente",
"Power|Poder|Energía|Potencia",
"Present|Regalo|Presente|Obsequio",
"President|Presidente|Mandatario|Jefe de Estado",
"Puddle|Charco|Poza|Acumulación de agua",
"Purse|Bolso|Cartera|Monedero",
"Quicksand|Arenas movedizas|Arena movediza|Arenal movedizo",
"Refrigerator|Refrigerador|Nevera|Frigorífico",
"Religion|Religión|Creencia religiosa|Fe",
"Report|Informe|Reporte|Relato",
"River|Río|Corriente|Curso de agua",
"Safe|Caja fuerte|Seguro|Protegido",
"Salad|Ensalada|Ensalada mixta|Plato de vegetales",
"Sand|Arena|Arenilla|Granos de arena",
"Sandwich|Sándwich|Emparedado|Bocadillo",
"School|Escuela|Colegio|Centro educativo",
"Seashell|Concha marina|Caracola|Concha de mar",
"Secret|Secreto|Misterio|Confidencia",
"Shoe|Zapato|Calzado|Zapatilla",
"Shopping Cart|Carrito de compras|Carrito de supermercado|Carro de compras",
"Shovel|Pala|Pala de cavar|Herramienta de excavación",
"Sink|Fregadero|Lavabo|Pila",
"Skyscraper|Rascacielos|Edificio alto|Torre",
"Smoke|Humo|Humareda|Humo denso",
"Sofa|Sofá|Sillón|Diván",
"Solar System|Sistema solar|Sistema planetario|Sistema del Sol",
"Song|Canción|Tema musical|Canto",
"Soul|Alma|Espíritu|Esencia",
"Soup|Sopa|Caldo|Sopa líquida",
"Space|Espacio|Espacio exterior|Universo",
"Spam|Spam|Correo basura|Mensajes no deseados",
"Spider Web|Telaraña|Red de araña|Tela de araña",
"Sponge|Esponja|Esponja de limpieza|Esponja absorbente",
"Spring|Primavera|Manantial|Resorte",
"Square|Cuadrado|Plaza|Casilla",
"Statue of Liberty|Estatua de la Libertad|Estatua de la Libertad de Nueva York|Monumento de la Libertad",
"Stocking|Media|Calcetín largo|Media navideña",
"Stomach|Estómago|Vientre|Barriga",
"Stone|Piedra|Roca|Pedrusco",
"Story|Historia|Cuento|Relato",
"Stuffing|Relleno|Relleno de comida|Guarnición de relleno",
"Submarine|Submarino|Nave submarina|Embarcación submarina",
"Suitcase|Maleta|Valija|Equipaje",
"Supermarket|Supermercado|Tienda de comestibles|Mercado",
"Taxi|Taxi|Automóvil de alquiler|Coche de servicio",
"Tank|Tanque|Depósito|Tanque militar",
"Tear|Lágrima|Desgarro|Rasgadura",
"Television|Televisión|Televisor|TV",
"Test Tube|Tubo de ensayo|Tubo experimental|Tubo de laboratorio",
"Theater|Teatro|Sala de teatro|Cine*",
"Thief|Ladrón|Ratero|Roba-cosas",
"Thoughts|Pensamientos|Ideas|Reflexiones",
"Toilet|Inodoro|Retrete|Sanitario",
"Tooth|Diente|Muela|Pieza dental",
"Top Hat|Sombrero de copa|Chistera|Sombrero alto",
"Tornado|Tornado|Tornado de viento|Torbellino",
"Tourist|Turista|Viajero|Visitante",
"Tractor Trailer|Camión con remolque|Tráiler|Cabezal con remolque",
"Traffic|Tráfico|Tránsito|Circulación",
"Trailer Park|Parque de casas móviles|Zona de casas rodantes|Parque de remolques",
"Trouble|Problema|Problemas|Dificultad",
"Trunk|Maletero|Baúl|Tronco",
"Tunnel|Túnel|Pasadizo|Galería",
"Turkey|Pavo|Guajolote|Pavo doméstico",
"Turtle|Tortuga|Tortuga terrestre|Tortuga marina",
"Universe|Universo|Cosmos|Creación",
"Vacuum|Aspiradora|Vacío|Aspirador",
"Vase|Jarrón|Florero|Vaso decorativo",
"Vein|Vena|Vaso sanguíneo|Conducto venoso",
"Venus Fly Trap|Venus atrapamoscas|Planta carnívora|Dionaea",
"Virus|Virus|Agente viral|Microorganismo viral",
"Vise|Tornillo de banco|Prensa de banco|Mordaza",
"Voice|Voz|Voces|Tono de voz",
"Washington|Washington|Washington D. C.|Estado de Washington",
"Water|Agua|Líquido|Agua potable",
"Whale|Ballena|Cetáceo|Ballena marina",
"White House|Casa Blanca|Residencia presidencial|Sede presidencial",
"Will|Voluntad|Testamento|Deseo",
"Window|Ventana|Ventanal|Cristal",
"Wood|Madera|Leña|Madero",
"Word|Palabra|Término|Vocablo",
"World|Mundo|Planeta|Tierra",
"Worm|Gusano|Larva|Gusano de tierra"
];
